CREATE DATABASE IF NOT EXISTS db_loja;

USE db_loja;

CREATE TABLE tb_funcionario(
id_funcionario INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL UNIQUE,
cpf VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_endereco(
FUNCIONARIO_id_funcionario INT NOT NULL,
id_endereco INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
rua VARCHAR(50) NOT NULL,
bairro VARCHAR(50) NOT NULL,
numero_casa INT NOT NULL,
cidade VARCHAR(30) NOT NULL,
estado VARCHAR(2) NOT NULL,
FOREIGN KEY (FUNCIONARIO_id_funcionario) REFERENCES tb_funcionario(id_funcionario)
);